name: PR Builds

on:
  pull_request:

env:
  BUILD_TYPE: pr
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      build_type: pr
